### PR TITLE
added depedency from requirement.txt to setup.cfg

### PR DESCRIPTION
**Pull request by saurabh-pal-dn**

### CODE REVIEW

**Comment by Raahul-Singh** [comment]
Hmm. I wonder if we can add doctests here to ensure the docs are building properly.

**Comment by Raahul-Singh** [comment]
@Sayam753 I'm merging this here, we can add the tests on a separate PR.

**Comment by Raahul-Singh** [comment]
Oh and @bestpal97 please add a changelog!

**Comment by kakirastern** [comment]
I have fixed this in another issue due to a need to set up RTD urgently. Apologies for the delay in response but much appreciate your work @Sayam753!

**Pull request closed without merging**
